---
- name: "config.setting.proxy: Ensure state"
  vars:
    proxy_settings:
      AWX_TASK_ENV:
        http_proxy: "{{ tower_config.setting.proxy.http_proxy | default(omit) }}"
        https_proxy: "{{ tower_config.setting.proxy.https_proxy | default(omit) }}"
        no_proxy: "{{ tower_config.setting.proxy.no_proxy | default(omit) }}"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/settings/all/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl | default(omit) }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: PATCH
    body: "{{ proxy_settings }}"
    body_format: "{{ tower_config.format }}"
  register: reg_config_setting_proxy
