---
- name: "config.organization: [ {{ tower_config_organization.name }} ]"
  tower_organization:
    tower_host: "{{ tower_config.host | default(omit) }}"
    tower_username: "{{ tower_config.username | default(omit) }}"
    tower_password: "{{ tower_config.password | default(omit) }}"
    tower_verify_ssl: "{{ tower_config.verify_ssl | default(omit) }}"
    name: "{{ tower_config_organization.name }}"
    description: "{{ tower_config_organization.description | default(omit) }}"
    state: "{{ tower_config_organization.state | default('present') }}"

- name: "config.organization: Process [ instance_groups ]"
  when: tower_config_organization.instance_groups is defined
  include_tasks: "instance_groups.yml"
  loop: "{{ tower_config_organization.instance_groups | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_instance_groups
    label: "{{ tower_config_organization_instance_groups.name }}"

- name: "config.organization: Process [ users ]"
  when: tower_config_organization.users is defined
  include_tasks: "user.yml"
  loop: "{{ tower_config_organization.users | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_user
    label: "{{ tower_config_organization_user.name }}"

- name: "config.organization: Process [ teams ]"
  when: tower_config_organization.teams is defined
  include_tasks: "team.yml"
  loop: "{{ tower_config_organization.teams | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_team
    label: "{{ tower_config_organization_team.name }}"

- name: "config.organization: Process [ credentials ]"
  when: tower_config_organization.credentials is defined
  include_tasks: "credential.yml"
  loop: "{{ tower_config_organization.credentials | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_credential
    label: "{{ tower_config_organization_credential.name }}"

- name: "config.organization: Process [ projects ]"
  when: tower_config_organization.projects is defined
  include_tasks: "project.yml"
  loop: "{{ tower_config_organization.projects | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_project
    label: "{{ tower_config_organization_project.name }}"

- name: "config.organization: Process [ inventories ]"
  when: tower_config_organization.inventories is defined
  include_tasks: "inventory.yml"
  loop: "{{ tower_config_organization.inventories | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_inventory
    label: "{{ tower_config_organization_inventory.name }}"

- name: "config.organization: Process [ hosts ]"
  when: tower_config_organization.hosts is defined
  include_tasks: "host.yml"
  loop: "{{ tower_config_organization.hosts | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_host
    label: "{{ tower_config_organization_host.name }}"

- name: "config.organization: Process [ job_templates ]"
  when: tower_config_organization.job_templates is defined
  include_tasks: "job_template.yml"
  loop: "{{ tower_config_organization.job_templates | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_job_template
    label: "{{ tower_config_organization_job_template.name }}"

### Buggy module
# - name: "config.organization: Process [ permissions ]"
#   when: tower_config_organization.permissions is sequence
#   include_tasks: "permission.yml"
#   loop: "{{ tower_config_organization.permissions }}"
#   loop_control:
#     loop_var: tower_config_organization_permission
#     label: "{{ tower_config_organization_permission.team | default(tower_config_organization_permission.user) }}"

- name: "config.organization: Process [ permissions ] with tower-cli"
  when: tower_config_organization.permissions is defined
  include_tasks: "permission-cli.yml"
  loop: "{{ tower_config_organization.permissions | default ([]) }}"
  loop_control:
    loop_var: tower_config_organization_permission
    label: "{{ tower_config_organization_permission.team | default(tower_config_organization_permission.user) }}"
