---
- name: "config.organization.inventory.source: [ {{ tower_config_organization_inventory_source.name }} ]"
  tower_inventory_source:
    tower_host: "{{ tower_config.host | default(omit) }}"
    tower_username: "{{ tower_config.username | default(omit) }}"
    tower_password: "{{ tower_config.password | default(omit) }}"
    tower_verify_ssl: "{{ tower_config.verify_ssl | default(omit) }}"
    name: "{{ tower_config_organization_inventory_source.name }}"
    description: "{{ tower_config_organization_inventory_source.description | default(omit) }}"
    state: "{{ tower_config_organization_inventory_source.state | default(omit) }}"
    credential: "{{ tower_config_organization_inventory_source.credential | default(omit) }}"
    group_by: "{{ tower_config_organization_inventory_source.group_by | default(omit) }}"
    instance_filters: "{{ tower_config_organization_inventory_source.instance_filter | default(omit) }}"
    inventory: "{{ tower_config_organization_inventory.name }}"
    overwrite: "{{ tower_config_organization_inventory_source.overwrite | default(omit) }}"
    overwrite_vars: "{{ tower_config_organization_inventory_source.overwrite_vars | default(omit) }}"
    source: "{{ tower_config_organization_inventory_source.source }}"
    source_path: "{{ tower_config_organization_inventory_source.source_path | default(omit) }}"
    source_project: "{{ tower_config_organization_inventory_source.source_project | default(omit) }}"
    source_regions: "{{ tower_config_organization_inventory_source.source_regions | default(omit) }}"
    source_script: "{{ tower_config_organization_inventory_source.source_script | default(omit) }}"
    source_vars: "{{ tower_config_organization_inventory_source.source_vars | default(omit) }}"
    update_on_launch: "{{ tower_config_organization_inventory_source.update_on_launch | default(omit) }}"
    update_on_project_update: "{{ tower_config_organization_inventory_source.update_on_project_update
                              | default(omit) }}"
  async: 15
  poll: 1
